### PR TITLE
Noetic support

### PR DESCRIPTION
**Pull request by UtQ67**

### CODE REVIEW

**Comment by cmuell89** [comment]
@UtQ67 , could you describe a little bit as to the changes you made to support ROS Noetic? Does this PR enable support for Python3?

**Comment by UtQ67** [comment]
@cmuell89 Yes, this PR enables support for Python3 by adding `catkin_install_python` to the CMakeList.txt

Keep in mind to add your python scripts that are executable into the catkin_install_python, so ROS can configure the correct python version, depending on your ROS version.
If you are using one ROS version there is no need to do that.

**Comment by awesome-manuel** [comment]
A lot of changes were obiously done using search and replace. This leads to many lines like this:
```
print(("..."))
```

**Comment by UtQ67** [comment]
> A lot of changes were obiously done using search and replace. This leads to many lines like this:
> 
> ```
> print(("..."))
> ```
> 
> Also if Noetic is now supported, the README should be changed accordingly.

Issue is addressed in #161

**Pull request merged**
